version: '3'

services:
  # db:
  #   image: mysql:8.0
  #   restart: always
  #   environment:
  #     # MYSQL_HOST: localhost
  #     # MYSQL_USER: root
  #     MYSQL_ROOT_PASSWORD: 61246323
  #   volumes:
  #     - data:/var/lib/mysql
  #   ports:
  #     - "3306:3306"

  # phpmyadmin:
  #   image: phpmyadmin:5.1.1
  #   restart: always
  #   ports:
  #     - "8080:80"
  #   environment:
  #     - PMA_ARBITRARY=1
  #   depends_on:
  #     - db

  minio:
    image: minio/minio
    volumes:
      - minio:/data:rw
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "minio"
      MINIO_ROOT_PASSWORD: 61246323
      MINIO_CONSOLE_ADDRESS: ":9001"

    command: server /data
  # app:
  #   image: test-node:1.0.0
  #   depends_on:
  #     - db
  #   ports:
  #     - 3000:3000

volumes:
  data:
  minio:
    driver: local

